In [1]:
import numpy as np
import pandas as pd

In [5]:
df=pd.read_csv('train.csv',usecols=['GarageQual','FireplaceQu','SalePrice'])

In [23]:
df

     FireplaceQu GarageQual  SalePrice no_na
0            NaN         TA     208500    TA
1             TA         TA     181500    TA
2             TA         TA     223500    TA
3             Gd         TA     140000    TA
4             TA         TA     250000    TA
...          ...        ...        ...   ...
1455          TA         TA     175000    TA
1456          TA         TA     210000    TA
1457          Gd         TA     266500    TA
1458         NaN         TA     142125    TA
1459         NaN         TA     147500    TA

[1460 rows x 4 columns]

In [10]:
df.isnull().mean()*100

FireplaceQu    47.260274
GarageQual      5.547945
SalePrice       0.000000
dtype: float64

In [11]:
df['GarageQual'].value_counts()

GarageQual
TA    1311
Fa      48
Gd      14
Ex       3
Po       3
Name: count, dtype: int64

In [26]:
df['GarageQual'].mode()

0    TA
Name: GarageQual, dtype: object

In [18]:
df['GarageQual'].fillna('TA',inplace=True)

In [24]:
df.head(10)

  FireplaceQu GarageQual  SalePrice no_na
0         NaN         TA     208500    TA
1          TA         TA     181500    TA
2          TA         TA     223500    TA
3          Gd         TA     140000    TA
4          TA         TA     250000    TA
5         NaN         TA     143000    TA
6          Gd         TA     307000    TA
7          TA         TA     200000    TA
8          TA         Fa     129900    Fa
9          TA         Gd     118000    Gd

In [25]:
df.isnull().mean()*100

FireplaceQu    47.260274
GarageQual      0.000000
SalePrice       0.000000
no_na           0.000000
dtype: float64

In [27]:
df['FireplaceQu'].fillna('missing',inplace=True)

C:\Users\User\AppData\Local\Temp\ipykernel_21636\2526449392.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['FireplaceQu'].fillna('missing',inplace=True)

In [30]:
df['FireplaceQu'].value_counts()

FireplaceQu
missing    690
Gd         380
TA         313
Fa          33
Ex          24
Po          20
Name: count, dtype: int64