In [21]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

In [22]:
df=pd.read_csv('train.csv')

In [23]:
df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [24]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [25]:
df

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [26]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=False)

In [27]:
X_train

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
140       3  female   NaN      0      2  15.2458        C
439       2    male  31.0      0      0  10.5000        S
817       2    male  31.0      1      1  37.0042        C
378       3    male  20.0      0      0   4.0125        C
491       3    male  21.0      0      0   7.2500        S
..      ...     ...   ...    ...    ...      ...      ...
835       1  female  39.0      1      1  83.1583        C
192       3  female  19.0      1      0   7.8542        S
629       3    male   NaN      0      0   7.7333        Q
559       3  female  36.0      1      0  17.4000        S
684       2    male  60.0      1      1  39.0000        S

[712 rows x 7 columns]

In [28]:
y_train

140    0
439    0
817    0
378    0
491    0
      ..
835    1
192    1
629    0
559    1
684    0
Name: Survived, Length: 712, dtype: int64

In [29]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [30]:
si_age=SimpleImputer()
si_embarked=SimpleImputer(strategy='most_frequent')
X_train_age=si_age.fit_transform(X_train[['Age']])
X_train_embarked=si_embarked.fit_transform(X_train[['Embarked']])
X_test_age=si_age.transform(X_test[['Age']])
X_test_embarked=si_embarked.transform(X_test[['Embarked']])

In [31]:
ohe_sex=OneHotEncoder(sparse_output=False,handle_unknown='ignore')
ohe_embarked=OneHotEncoder(sparse_output=False,handle_unknown='ignore')
X_train_sex=ohe_sex.fit_transform(X_train[['Sex']])
X_train_embarked=ohe_embarked.fit_transform(X_train_embarked)
X_test_sex=ohe_sex.transform(X_test[['Sex']])
X_test_embarked=ohe_embarked.transform(X_test_embarked)

In [32]:
X_train_rem=X_train.drop(columns=['Sex','Age','Embarked'])

In [33]:
X_test_rem=X_test.drop(columns=['Sex','Age','Embarked'])

In [34]:
X_train_transformed=np.concatenate((X_train_rem,X_train_age,X_train_sex,X_train_embarked),axis=1)
X_test_transformed=np.concatenate((X_test_rem,X_test_age,X_test_sex,X_test_embarked),axis=1)